In [4]:
import pandas as pd
import numpy as np

In [5]:
l = [32, 564, 23, 65, 75]


s = pd.Series(l)

In [6]:
s

0     32
1    564
2     23
3     65
4     75
dtype: int64

In [7]:
s = pd.Series(l, index=['a', 'b', 'c', 'd', 'e'])

In [8]:
s

a     32
b    564
c     23
d     65
e     75
dtype: int64

In [9]:
s = pd.Series(l, index=['a', 'b', 'c', 'd'])

ValueError: Length of values (5) does not match length of index (4)

In [12]:
s = pd.Series(l, index=range(3, 8))

In [13]:
s

3     32
4    564
5     23
6     65
7     75
dtype: int64

In [14]:
s

3     32
4    564
5     23
6     65
7     75
dtype: int64

In [16]:
s[3]

32

In [17]:
s[7]

75

In [18]:
s[8]

KeyError: 8

In [19]:
s

3     32
4    564
5     23
6     65
7     75
dtype: int64

In [20]:
s.index = ['a', 'b', 'c', 'd', 'e']

In [21]:
s

a     32
b    564
c     23
d     65
e     75
dtype: int64

In [22]:
s['a']

32

In [25]:
d = {"name":'khalid', 'class':9, 'age':20, 'program':"BSSE"}

stu = pd.Series(d)

In [26]:
stu

name       khalid
class           9
age            20
program      BSSE
dtype: object

In [27]:
stu['name']

'khalid'

In [28]:
stu['program']

'BSSE'

In [30]:
data = [[43, 23, 53], [63, 23, 56], [64, 23, 65]]

df = pd.DataFrame(data)

In [31]:
df

    0   1   2
0  43  23  53
1  63  23  56
2  64  23  65

In [32]:
student = {
    "Names":['ahmad', 'ali', 'salman', 'kamran', 'sohail'],
    'Ages':[21, 32, 32, 32, 23],
    'gpa':[3.5, 3.6, 3.0, 3.8, 2.9]
}

In [33]:
student

{'Names': ['ahmad', 'ali', 'salman', 'kamran', 'sohail'],
 'Ages': [21, 32, 32, 32, 23],
 'gpa': [3.5, 3.6, 3.0, 3.8, 2.9]}

In [38]:
df_stu = pd.DataFrame(student)

In [39]:
df_stu

    Names  Ages  gpa
0   ahmad    21  3.5
1     ali    32  3.6
2  salman    32  3.0
3  kamran    32  3.8
4  sohail    23  2.9

In [42]:
data = [[43, 23, 53], [63, 23, 56], [64, 23, 65]]

df = pd.DataFrame(data, index=['x', 'y', 'z'], columns=['a', 'b', 'c'])

In [43]:
df

    a   b   c
x  43  23  53
y  63  23  56
z  64  23  65

In [51]:
type(df['a'])

pandas.core.series.Series

In [48]:
df['b']

x    23
y    23
z    23
Name: b, dtype: int64

In [52]:
df.iloc[0]

a    43
b    23
c    53
Name: x, dtype: int64

In [53]:
df

    a   b   c
x  43  23  53
y  63  23  56
z  64  23  65

In [54]:
df.iloc[2]

a    64
b    23
c    65
Name: z, dtype: int64

In [55]:
df

    a   b   c
x  43  23  53
y  63  23  56
z  64  23  65

In [57]:
df.iloc[1, 2]

56

In [58]:
df.loc['x']

a    43
b    23
c    53
Name: x, dtype: int64

In [59]:
df

    a   b   c
x  43  23  53
y  63  23  56
z  64  23  65

In [60]:
df.loc['z']

a    64
b    23
c    65
Name: z, dtype: int64

In [61]:
df.loc['y', 'b']

23

### loading a datasert

In [62]:
path = r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\Titanic-Dataset.csv"

df = pd.read_csv(path)

In [63]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [64]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [65]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [66]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [67]:
df['Ticket']

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object

In [68]:
df.loc[:, "Pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [70]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [71]:
df.loc[2]

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [72]:
df.index = df['PassengerId']

In [73]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [74]:
df.loc[1]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 1, dtype: object

In [75]:
df['PassengerId']

PassengerId
1        1
2        2
3        3
4        4
5        5
      ...
887    887
888    888
889    889
890    890
891    891
Name: PassengerId, Length: 891, dtype: int64

In [76]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [77]:
df.loc[8]

PassengerId                                 8
Survived                                    0
Pclass                                      3
Name           Palsson, Master. Gosta Leonard
Sex                                      male
Age                                       2.0
SibSp                                       3
Parch                                       1
Ticket                                 349909
Fare                                   21.075
Cabin                                     NaN
Embarked                                    S
Name: 8, dtype: object

In [78]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [81]:
df['Survived'] == 1

PassengerId
1      False
2       True
3       True
4       True
5      False
       ...
887    False
888     True
889    False
890     True
891    False
Name: Survived, Length: 891, dtype: bool

In [82]:
df[df['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
876,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
880,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [83]:
survived = df[df['Survived'] == 1]

In [84]:
survived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
876,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
880,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [85]:
survived.shape

(342, 12)

In [86]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [87]:
df_city = pd.read_csv(r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\city_info.csv")

In [88]:
df_city

        city                     province campus_type
0   Peshawar           Khyber Pakhtunkhwa        Main
1     Lahore                       Punjab        Main
2    Karachi                        Sindh        Main
3  Islamabad  Islamabad Capital Territory   Satellite
4     Quetta                  Balochistan   Satellite
5     Multan                       Punjab   Satellite

In [89]:
df_city.shape

(6, 3)

In [91]:
df_city['city']

0     Peshawar
1       Lahore
2      Karachi
3    Islamabad
4       Quetta
5       Multan
Name: city, dtype: object

In [92]:
df_city['city'] == 'Peshawar'

0     True
1    False
2    False
3    False
4    False
5    False
Name: city, dtype: bool

In [93]:
df_city[df_city['city'] == 'Peshawar']

       city            province campus_type
0  Peshawar  Khyber Pakhtunkhwa        Main

In [94]:
l = [False, True, True, False, False, False]

In [95]:
df_city[l]

      city province campus_type
1   Lahore   Punjab        Main
2  Karachi    Sindh        Main

In [96]:
df_city

        city                     province campus_type
0   Peshawar           Khyber Pakhtunkhwa        Main
1     Lahore                       Punjab        Main
2    Karachi                        Sindh        Main
3  Islamabad  Islamabad Capital Territory   Satellite
4     Quetta                  Balochistan   Satellite
5     Multan                       Punjab   Satellite

In [97]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [98]:
df[df['Age'] <= 25]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
8,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
10,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
13,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
878,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
881,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [99]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [101]:
df[df['Age'] <= 25]['Name']

PassengerId
1                           Braund, Mr. Owen Harris
8                    Palsson, Master. Gosta Leonard
10              Nasser, Mrs. Nicholas (Adele Achem)
11                  Sandstrom, Miss. Marguerite Rut
13                   Saundercock, Mr. William Henry
                           ...
878                            Petroff, Mr. Nedelio
881    Shelley, Mrs. William (Imanita Parrish Hall)
883                    Dahlberg, Miss. Gerda Ulrika
885                          Sutehall, Mr. Henry Jr
888                    Graham, Miss. Margaret Edith
Name: Name, Length: 301, dtype: object

In [102]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [104]:
df['Fare'].mean()

32.204207968574636

In [105]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [111]:
female_above40 = df[(df["Sex"] == 'female') & (df['Age'] > 40)]

In [112]:
female_above40.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
12,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
16,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
53,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
133,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
168,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S

In [113]:
female_above40.shape

(48, 12)

In [114]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,,
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [115]:
df[['Name', "Age"]]

                                                          Name   Age
PassengerId
1                                      Braund, Mr. Owen Harris  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3                                       Heikkinen, Miss. Laina  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
5                                     Allen, Mr. William Henry  35.0
...                                                        ...   ...
887                                      Montvila, Rev. Juozas  27.0
888                               Graham, Miss. Margaret Edith  19.0
889                   Johnston, Miss. Catherine Helen "Carrie"   NaN
890                                      Behr, Mr. Karl Howell  26.0
891                                        Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [118]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [119]:
sdf = pd.read_csv(r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\students.csv")

In [120]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [121]:
sdf[sdf['scholarship'] == 1]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
10,S1141,Male,Lahore,BSEE,5,3.2,92.1,3.35,54.4,1
11,S1168,Male,KARACHI,BSSE,3,7.8,82.7,2.79,67.7,1
12,S1045,Female,Multan,BSEE,7,3.2,NaN,3.31,42.7,1
14,S1129,Female,Peshawar,BBA,8,3.6,87.9,3.79,69.0,1
17,S1166,Female,Multan,BSEE,7,7.4,80.0,3.21,64.0,1
...,...,...,...,...,...,...,...,...,...,...
171,S1136,Female,Lahore,BBA,5,5.9,68.8,2.93,64.8,1
172,S1042,Female,Karachi,BSSE,3,4.4,67.2,3.74,49.9,1
173,S1110,Male,Quetta,BBA,4,1.0,75.0,3.86,51.2,1
175,S1072,Female,Lahore,BSSE,4,4.8,70.5,2.88,65.1,1
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1

In [123]:
sdf['city'].unique()

array(['Quetta', 'Karachi', 'Lahore', 'PESHAWAR', 'Peshawar', 'KARACHI',
       'Multan', 'Islamabad'], dtype=object)

In [130]:
attendance_short = sdf['attendance'] < 75

In [131]:
attendance_short

0      False
1      False
2      False
3      False
4      False
       ...
179     True
180     True
181    False
182    False
183    False
Name: attendance, Length: 184, dtype: bool

In [132]:
sdf["Attendance Short"] = attendance_short

In [133]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance Short
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False
...,...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False

In [142]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance Short
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False
...,...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False

In [144]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance Short
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False
...,...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False

In [152]:
sdf.shape

(184, 11)

In [151]:
np.where(sdf['attendance'] < 75, "Yes", "No")

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No',
       'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes',
       'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No',
       'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'No', 'No'], dtype='<U3')

In [153]:
sdf["Status"] = np.where(sdf['attendance'] < 75, "Fail", "Pass")

In [154]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance Short,Status
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False,Pass
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False,Pass
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False,Pass
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False,Pass
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True,Fail
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True,Fail
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False,Pass
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False,Pass
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False,Pass

In [155]:
add = lambda x, y: x+y

In [156]:
add(3, 4)

7

In [162]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance Short,Status
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0,False,Pass
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False,Pass
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0,False,Pass
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0,False,Pass
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True,Fail
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True,Fail
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False,Pass
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False,Pass
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False,Pass

In [ ]:
def return_in_lower(s):
    return s.lower()

In [168]:
l = []
for city in sdf['city']:
    l.append(return_in_lower(city))

pd.Series(l)

0        quetta
1       karachi
2        lahore
3      peshawar
4        quetta
         ...
179    peshawar
180    peshawar
181      lahore
182    peshawar
183     karachi
Length: 184, dtype: object

In [169]:
sdf['city'].apply(return_in_lower)

0        quetta
1       karachi
2        lahore
3      peshawar
4        quetta
         ...
179    peshawar
180    peshawar
181      lahore
182    peshawar
183     karachi
Name: city, Length: 184, dtype: object

In [171]:
sdf['city'] = sdf['city'].apply(return_in_lower)

In [172]:
sdf

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,Attendance Short,Status
0,S1099,Female,quetta,BBA,1,8.1,87.5,1.91,68.5,0,False,Pass
1,S1179,Female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0,False,Pass
2,S1131,Female,lahore,BBA,7,4.0,96.9,NaN,68.7,0,False,Pass
3,S1024,Female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0,False,Pass
4,S1065,Male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0,False,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,True,Fail
180,S1151,Female,peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,True,Fail
181,S1067,Male,lahore,BSSE,7,1.4,82.0,2.14,65.3,0,False,Pass
182,S1025,Male,peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,False,Pass
183,S1175,Male,karachi,BSCS,1,6.3,75.5,2.04,57.8,0,False,Pass

In [173]:
sdf['city'].unique()

array(['quetta', 'karachi', 'lahore', 'peshawar', 'multan', 'islamabad'],
      dtype=object)

In [174]:
sdf['gender'].apply(lambda s: s.lower())

0      female
1      female
2      female
3      female
4        male
        ...
179    female
180    female
181      male
182      male
183      male
Name: gender, Length: 184, dtype: object