In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\laptops_test.csv")

In [3]:
df.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,15-bs053od (i7-7500U/6GB/1TB/W10),Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Rog GL753VE-DS74,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,Inspiron 7579,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Portege Z30-C-1CV,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,IdeaPad 320-15ABR,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [4]:
df.shape

(325, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    object
 1   Model Name                325 non-null    object
 2   Category                  325 non-null    object
 3   Screen Size               325 non-null    object
 4   Screen                    325 non-null    object
 5   CPU                       325 non-null    object
 6   RAM                       325 non-null    object
 7    Storage                  325 non-null    object
 8   GPU                       325 non-null    object
 9   Operating System          325 non-null    object
 10  Operating System Version  291 non-null    object
 11  Weight                    325 non-null    object
 12  Price                     325 non-null    float64
dtypes: float64(1), object(12)
memory usage: 33.1+ KB

In [6]:
df['Manufacturer'].unique()

array(['HP', 'Asus', 'Dell', 'Toshiba', 'Lenovo', 'Fujitsu', 'Acer',
       'MSI', 'Vero', 'Apple', 'Razer', 'Samsung'], dtype=object)

In [7]:
df.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,15-bs053od (i7-7500U/6GB/1TB/W10),Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Rog GL753VE-DS74,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,Inspiron 7579,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Portege Z30-C-1CV,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,IdeaPad 320-15ABR,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [9]:
df['Model Name'].unique().shape

(197,)

In [11]:
df.drop("Model Name", axis=1)

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0
...,...,...,...,...,...,...,...,...,...,...,...,...
320,Lenovo,2 in 1 Convertible,"14.0""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,5673096.0
321,Lenovo,2 in 1 Convertible,"13.3""",IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,13329108.0
322,Lenovo,Notebook,"14.0""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,2036268.0
323,HP,Notebook,"15.6""",1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,6793488.0
324,Asus,Notebook,"15.6""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,3281148.0

In [12]:
df.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,15-bs053od (i7-7500U/6GB/1TB/W10),Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Rog GL753VE-DS74,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,Inspiron 7579,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Portege Z30-C-1CV,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,IdeaPad 320-15ABR,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [13]:
df.drop('Model Name', axis=1, inplace=True)

In [14]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,Notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,Gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 Convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,Notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,Notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [16]:
df['Category'].unique()

array(['Notebook', 'Gaming', '2 in 1 Convertible', 'Netbook', 'Ultrabook',
       'Workstation'], dtype=object)

In [17]:
df['Category'].nunique()

6

In [21]:
df[df['Category'] == "Netbook"].shape

(8, 12)

In [22]:
df['Category'].apply(lambda s: s.lower())

0                notebook
1                  gaming
2      2 in 1 convertible
3                notebook
4                notebook
              ...
320    2 in 1 convertible
321    2 in 1 convertible
322              notebook
323              notebook
324              notebook
Name: Category, Length: 325, dtype: object

In [23]:
df["Category"] = df['Category'].apply(lambda s: s.lower())

In [24]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [25]:
df['Category'].unique()

array(['notebook', 'gaming', '2 in 1 convertible', 'netbook', 'ultrabook',
       'workstation'], dtype=object)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    object
 1   Category                  325 non-null    object
 2   Screen Size               325 non-null    object
 3   Screen                    325 non-null    object
 4   CPU                       325 non-null    object
 5   RAM                       325 non-null    object
 6    Storage                  325 non-null    object
 7   GPU                       325 non-null    object
 8   Operating System          325 non-null    object
 9   Operating System Version  291 non-null    object
 10  Weight                    325 non-null    object
 11  Price                     325 non-null    float64
dtypes: float64(1), object(11)
memory usage: 30.6+ KB

In [27]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,notebook,"15.6""",1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,gaming,"17.3""",Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 convertible,"15.6""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,notebook,"13.3""",Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,notebook,"15.6""",Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [28]:
s = '17.3"'

In [31]:
float(s.replace('"', ""))

17.3

In [32]:
df['Screen Size'] = df['Screen Size'].apply(lambda s: s.replace('"', ""))

In [33]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    object
 1   Category                  325 non-null    object
 2   Screen Size               325 non-null    object
 3   Screen                    325 non-null    object
 4   CPU                       325 non-null    object
 5   RAM                       325 non-null    object
 6    Storage                  325 non-null    object
 7   GPU                       325 non-null    object
 8   Operating System          325 non-null    object
 9   Operating System Version  291 non-null    object
 10  Weight                    325 non-null    object
 11  Price                     325 non-null    float64
dtypes: float64(1), object(11)
memory usage: 30.6+ KB

In [38]:
df['Screen Size'] = df['Screen Size'].astype(float)

In [39]:
df['Screen Size'].dtype

dtype('float64')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    object
 1   Category                  325 non-null    object
 2   Screen Size               325 non-null    float64
 3   Screen                    325 non-null    object
 4   CPU                       325 non-null    object
 5   RAM                       325 non-null    object
 6    Storage                  325 non-null    object
 7   GPU                       325 non-null    object
 8   Operating System          325 non-null    object
 9   Operating System Version  291 non-null    object
 10  Weight                    325 non-null    object
 11  Price                     325 non-null    float64
dtypes: float64(2), object(10)
memory usage: 30.6+ KB

In [41]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,notebook,15.6,Full HD 1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [43]:
type(df.iloc[2, 3])

str

In [46]:
df.iloc[2, 3].split()[-1]

'1920x1080'

In [47]:
df['Screen'].apply(lambda s: s.split()[-1])

0       1366x768
1      1920x1080
2      1920x1080
3      1920x1080
4      1920x1080
         ...
320    1920x1080
321    3200x1800
322     1366x768
323     1366x768
324     1366x768
Name: Screen, Length: 325, dtype: object

In [48]:
df['Screen'] = df['Screen'].apply(lambda s: s.split()[-1])

In [49]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0
1,Asus,gaming,17.3,1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0
2,Dell,2 in 1 convertible,15.6,1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0
3,Toshiba,notebook,13.3,1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0
4,Lenovo,notebook,15.6,1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0

In [50]:
df['CPU'].unique()

array(['Intel Core i7 7500U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 6200U 2.3GHz', 'AMD A12-Series 9720P 3.6GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core M 6Y75 1.2GHz',
       'Intel Core i3 6006U 2GHz', 'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Core i5 6300U 2.4GHz',
       'Intel Core i7 6600U 2.6GHz', 'Intel Core i5 7300HQ 2.5GHz',
       'Intel Core i7 6500U 2.5GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'Intel Core i3 6100U 2.3GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Atom X5-Z8350 1.44GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core i7 6700HQ 2.6GHz',
       'Intel Celeron Dual Core N3060 1.6GHz',
       'Intel Core i5 7200U 2.7GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Core M 1.1GHz', 'Intel Core i5 6300HQ 2.3GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz',
       'Intel Core i5 8250U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'AMD A6-Series 9220 2.5GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i3 6006U 2.0GHz', 'Intel Core i7 7560U 2.4GHz',
       'Intel Core i7 6500U 2.50GHz', 'AMD E-Series 7110 1.8GHz',
       'AMD A6-Series A6-9220 2.5GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 1.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 1.6GHz',
       'Intel Core i5 7Y54 1.2GHz', 'Intel Core M 6Y30 0.9GHz',
       'AMD A9-Series 9410 2.9GHz'], dtype=object)

In [51]:
v = 'Intel Core i5 8250U 1.6GHz'.split()

In [52]:
v

['Intel', 'Core', 'i5', '8250U', '1.6GHz']

In [53]:
df['CPU'].apply(lambda s: s.split())

0                 [Intel, Core, i7, 7500U, 2.7GHz]
1                [Intel, Core, i7, 7700HQ, 2.8GHz]
2                 [Intel, Core, i7, 7500U, 2.7GHz]
3                 [Intel, Core, i5, 6200U, 2.3GHz]
4                 [AMD, A12-Series, 9720P, 3.6GHz]
                          ...
320               [Intel, Core, i7, 6500U, 2.5GHz]
321               [Intel, Core, i7, 6500U, 2.5GHz]
322    [Intel, Celeron, Dual, Core, N3050, 1.6GHz]
323               [Intel, Core, i7, 6500U, 2.5GHz]
324    [Intel, Celeron, Dual, Core, N3050, 1.6GHz]
Name: CPU, Length: 325, dtype: object

In [54]:
df['CPU'].apply(lambda s: s.split()[0])

0      Intel
1      Intel
2      Intel
3      Intel
4        AMD
       ...
320    Intel
321    Intel
322    Intel
323    Intel
324    Intel
Name: CPU, Length: 325, dtype: object

In [55]:
df["company"] = df['CPU'].apply(lambda s: s.split()[0])

In [56]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel
1,Asus,gaming,17.3,1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel
2,Dell,2 in 1 convertible,15.6,1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel
3,Toshiba,notebook,13.3,1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel
4,Lenovo,notebook,15.6,1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD

In [57]:
df['Core'] = df['CPU'].apply(lambda s: s.split()[-3])

In [58]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,Core
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7
1,Asus,gaming,17.3,1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7
2,Dell,2 in 1 convertible,15.6,1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7
3,Toshiba,notebook,13.3,1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5
4,Lenovo,notebook,15.6,1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series

In [59]:
df["Generation"] = df['CPU'].apply(lambda s: s.split()[-2])

In [61]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,Core,Generation
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U
1,Asus,gaming,17.3,1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ
2,Dell,2 in 1 convertible,15.6,1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U
3,Toshiba,notebook,13.3,1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U
4,Lenovo,notebook,15.6,1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P

In [62]:
df["Freq"] = df['CPU'].apply(lambda s: s.split()[-1])

In [63]:
df.head()

,Manufacturer,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,HP,notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,Asus,gaming,17.3,1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,Dell,2 in 1 convertible,15.6,1920x1080,Intel Core i7 7500U 2.7GHz,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,Toshiba,notebook,13.3,1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,Lenovo,notebook,15.6,1920x1080,AMD A12-Series 9720P 3.6GHz,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [64]:
df.drop("CPU", axis=1, inplace=True)

In [65]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,HP,notebook,15.6,1366x768,6GB,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,Asus,gaming,17.3,1920x1080,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,Dell,2 in 1 convertible,15.6,1920x1080,12GB,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,Toshiba,notebook,13.3,1920x1080,4GB,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,Lenovo,notebook,15.6,1920x1080,6GB,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [66]:
df['RAM'].unique()

array(['6GB', '16GB', '12GB', '4GB', '8GB', '2GB', '64GB', '32GB'],
      dtype=object)

In [69]:
df['RAM'] = df['RAM'].apply(lambda s: s.replace("GB", ""))

In [70]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,HP,notebook,15.6,1366x768,6,1TB HDD,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,Asus,gaming,17.3,1920x1080,16,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,Dell,2 in 1 convertible,15.6,1920x1080,12,512GB SSD,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,Toshiba,notebook,13.3,1920x1080,4,128GB SSD,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,Lenovo,notebook,15.6,1920x1080,6,256GB SSD,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [72]:
df.columns

Index(['Manufacturer', 'Category', 'Screen Size', 'Screen', 'RAM', ' Storage',
       'GPU', 'Operating System', 'Operating System Version', 'Weight',
       'Price', 'company', 'Core', 'Generation', 'Freq'],
      dtype='object')

In [73]:
df.drop(" Storage", axis=1, inplace=True)

In [74]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,GPU,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,HP,notebook,15.6,1366x768,6,Intel HD Graphics 620,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,Asus,gaming,17.3,1920x1080,16,Nvidia GeForce GTX 1050 Ti,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,Dell,2 in 1 convertible,15.6,1920x1080,12,Intel HD Graphics 620,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,Toshiba,notebook,13.3,1920x1080,4,Intel HD Graphics 520,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,Lenovo,notebook,15.6,1920x1080,6,AMD Radeon 530,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [75]:
df.drop("GPU", axis=1, inplace=True)

In [76]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,HP,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,Asus,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,Dell,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,Toshiba,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,Lenovo,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [77]:
df['Manufacturer'].unique()

array(['HP', 'Asus', 'Dell', 'Toshiba', 'Lenovo', 'Fujitsu', 'Acer',
       'MSI', 'Vero', 'Apple', 'Razer', 'Samsung'], dtype=object)

In [83]:
def numerical_conversion(s):
    match s:
        case "HP":
            return 1
        case "Asus":
            return 2
        case "Dell":
            return 3
        case "Toshiba":
            return 4
        case "Fujitsu":
            return 5
        case "Acer":
            return 6
        case "MSI":
            return 7
        case "Vero":
            return 8
        case "Apple":
            return 9
        case "Razer":
            return 10
        case "Samsung":
            return 11
        case "Lenovo":
            return 12

In [81]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,HP,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,Asus,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,Dell,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,Toshiba,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,Lenovo,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [84]:
df["Manufacturer"] = df["Manufacturer"].apply(numerical_conversion)

In [85]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,1,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,2,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,3,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,4,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,12,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [87]:
df["Operating System"].unique()

array(['Windows', 'No OS', 'Chrome OS', 'Mac OS', 'Linux', 'Android'],
      dtype=object)

In [88]:
df['company'].unique()

array(['Intel', 'AMD', 'Samsung'], dtype=object)

In [90]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,1,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,2,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,3,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,4,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,12,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [91]:
company_incod = pd.get_dummies(df['company'])

In [92]:
company_incod

       AMD  Intel  Samsung
0    False   True    False
1    False   True    False
2    False   True    False
3    False   True    False
4     True  False    False
..     ...    ...      ...
320  False   True    False
321  False   True    False
322  False   True    False
323  False   True    False
324  False   True    False

[325 rows x 3 columns]

In [ ]:
pd.concat((df, company_incod), axis=1)

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq,AMD,Intel,Samsung
0,1,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz,False,True,False
1,2,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz,False,True,False
2,3,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz,False,True,False
3,4,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz,False,True,False
4,12,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,12,2 in 1 convertible,14.0,1920x1080,4,Windows,10,1.8kg,5673096.0,Intel,i7,6500U,2.5GHz,False,True,False
321,12,2 in 1 convertible,13.3,3200x1800,16,Windows,10,1.3kg,13329108.0,Intel,i7,6500U,2.5GHz,False,True,False
322,12,notebook,14.0,1366x768,2,Windows,10,1.5kg,2036268.0,Intel,Core,N3050,1.6GHz,False,True,False
323,1,notebook,15.6,1366x768,6,Windows,10,2.19kg,6793488.0,Intel,i7,6500U,2.5GHz,False,True,False
324,2,notebook,15.6,1366x768,4,Windows,10,2.2kg,3281148.0,Intel,Core,N3050,1.6GHz,False,True,False

In [96]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq
0,1,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz
1,2,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz
2,3,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz
3,4,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz
4,12,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz

In [97]:
df = pd.concat((df, company_incod), axis=1)

In [98]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,company,Core,Generation,Freq,AMD,Intel,Samsung
0,1,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,Intel,i7,7500U,2.7GHz,False,True,False
1,2,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,Intel,i7,7700HQ,2.8GHz,False,True,False
2,3,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,Intel,i7,7500U,2.7GHz,False,True,False
3,4,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,Intel,i5,6200U,2.3GHz,False,True,False
4,12,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,AMD,A12-Series,9720P,3.6GHz,True,False,False

In [110]:
df.drop("company", axis=1, inplace=True)

KeyError: "['company'] not found in axis"

In [ ]:
df.head()

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,Core,Generation,Freq,AMD,Intel,Samsung
0,1,notebook,15.6,1366x768,6,Windows,10,2.04kg,5148468.0,i7,7500U,2.7GHz,False,True,False
1,2,gaming,17.3,1920x1080,16,Windows,10,2.99kg,15552108.0,i7,7700HQ,2.8GHz,False,True,False
2,3,2 in 1 convertible,15.6,1920x1080,12,Windows,10,2.19kg,11550708.0,i7,7500U,2.7GHz,False,True,False
3,4,notebook,13.3,1920x1080,4,Windows,7,1.2kg,10625940.0,i5,6200U,2.3GHz,False,True,False
4,12,notebook,15.6,1920x1080,6,Windows,10,2.2kg,4881708.0,A12-Series,9720P,3.6GHz,True,False,False

In [ ]:
df['Operating System'].unique()

array(['Windows', 'No OS', 'Chrome OS', 'Mac OS', 'Linux', 'Android'],
      dtype=object)

In [ ]:
df[df['Operating System'] == "No OS"].shape

(14, 15)

In [ ]:
df['Operating System'].mode()

0    Windows
Name: Operating System, dtype: object

In [ ]:
df['Operating System'].replace("No OS", "Windows", inplace=True)

In [111]:
df["Operating System"].unique()

array(['Windows', 'Chrome OS', 'Mac OS', 'Linux', 'Android'], dtype=object)

In [113]:
df.describe(include="all")

,Manufacturer,Category,Screen Size,Screen,RAM,Operating System,Operating System Version,Weight,Price,Core,Generation,Freq,AMD,Intel,Samsung
count,325.000000,325,325.000000,325,325,325,291,325,3.250000e+02,325,325,325,325,325,325
unique,NaN,6,NaN,9,8,5,3,98,NaN,12,44,21,2,2,2
top,NaN,notebook,NaN,1920x1080,8,Windows,10,2.2kg,NaN,i7,7200U,2.5GHz,False,True,False
freq,NaN,178,NaN,186,136,301,252,23,NaN,140,40,78,311,310,324
mean,4.910769,NaN,14.908923,NaN,NaN,NaN,NaN,NaN,9.891671e+06,NaN,NaN,NaN,NaN,NaN,NaN
std,4.248606,NaN,1.446840,NaN,NaN,NaN,NaN,NaN,5.943217e+06,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,10.100000,NaN,NaN,NaN,NaN,NaN,1.547208e+06,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.000000,NaN,14.000000,NaN,NaN,NaN,NaN,NaN,5.317416e+06,NaN,NaN,NaN,NaN,NaN,NaN
50%,3.000000,NaN,15.600000,NaN,NaN,NaN,NaN,NaN,8.892000e+06,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.000000,NaN,15.600000,NaN,NaN,NaN,NaN,NaN,1.332022e+07,NaN,NaN,NaN,NaN,NaN,NaN
max,12.000000,NaN,17.300000,NaN,NaN,NaN,NaN,NaN,3.534570e+07,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              325 non-null    int64
 1   Category                  325 non-null    object
 2   Screen Size               325 non-null    float64
 3   Screen                    325 non-null    object
 4   RAM                       325 non-null    object
 5   Operating System          325 non-null    object
 6   Operating System Version  291 non-null    object
 7   Weight                    325 non-null    object
 8   Price                     325 non-null    float64
 9   Core                      325 non-null    object
 10  Generation                325 non-null    object
 11  Freq                      325 non-null    object
 12  AMD                       325 non-null    bool
 13  Intel                     325 non-null    bool
 14  Samsung                   325 non-null    bool
dtypes: bool(3), float64(2), int64(1), object(9)
memory usage: 31.5+ KB

In [118]:
df.to_csv(r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\clean_laptop.csv")

In [ ]:
df.to_

### Working With Student Dataset

In [119]:
df = pd.read_csv(r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\students.csv")

In [120]:
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   184 non-null    object
 1   gender       184 non-null    object
 2   city         184 non-null    object
 3   program      184 non-null    object
 4   semester     184 non-null    int64
 5   study_hours  179 non-null    float64
 6   attendance   168 non-null    float64
 7   prev_gpa     174 non-null    float64
 8   final_marks  184 non-null    float64
 9   scholarship  184 non-null    int64
dtypes: float64(4), int64(2), object(4)
memory usage: 14.5+ KB

In [122]:
df.shape

(184, 10)

In [124]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [125]:
df.describe()

,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
count,184.000000,179.000000,168.000000,174.000000,184.000000,184.000000
mean,4.777174,7.256983,82.155357,2.839655,65.119565,0.423913
std,2.285454,4.888808,10.498998,0.582331,11.508669,0.495525
min,1.000000,0.500000,54.200000,1.370000,32.100000,0.000000
25%,3.000000,3.650000,76.000000,2.460000,58.175000,0.000000
50%,5.000000,6.400000,82.700000,2.875000,65.700000,0.000000
75%,7.000000,8.850000,89.400000,3.257500,72.725000,1.000000
max,8.000000,30.000000,100.000000,4.000000,92.400000,1.000000

In [126]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [130]:
ndf = df.copy()
m = df['study_hours'].mean()
ndf['study_hours'].fillna(m, inplace=True)

C:\Users\Abbas\AppData\Local\Temp\ipykernel_43356\2115090296.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ndf['study_hours'].fillna(m, inplace=True)

In [ ]:
ndf.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     0
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [ ]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].mean())

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"D:\AI\Artificial-Intelligence-Machine-Learning-and-Deep-Learning-Corvit-Peshawar-2026\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\students.csv")

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   184 non-null    object
 1   gender       184 non-null    object
 2   city         184 non-null    object
 3   program      184 non-null    object
 4   semester     184 non-null    int64
 5   study_hours  179 non-null    float64
 6   attendance   168 non-null    float64
 7   prev_gpa     174 non-null    float64
 8   final_marks  184 non-null    float64
 9   scholarship  184 non-null    int64
dtypes: float64(4), int64(2), object(4)
memory usage: 14.5+ KB

In [134]:
df.isna().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [135]:
df.shape

(184, 10)

In [139]:
df = df.dropna(axis=0, subset=["study_hours"])

In [140]:
df.shape

(179, 10)

In [141]:
df.isna().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     0
attendance     15
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [142]:
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [144]:
pd.DataFrame(df.groupby(["gender"]))

           0                                                  1
0  (Female,)      student_id  gender      city program  seme...
1    (Male,)      student_id gender      city program  semes...
2  (female,)      student_id  gender       city program  sem...
3    (male,)      student_id gender      city program  semes...

In [146]:
df['gender'].replace("Female", 'female', inplace=True)
df['gender'].replace("Male", 'male', inplace=True)

In [147]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [149]:
pd.DataFrame(df.groupby('gender'))

        0                                                  1
0  female      student_id  gender      city program  seme...
1    male      student_id gender      city program  semes...

In [151]:
df.groupby("gender")['study_hours'].mean()

gender
female    7.364474
male      7.177670
Name: study_hours, dtype: float64

In [154]:
df.groupby("gender")['study_hours'].agg(["mean", "median"])

            mean  median
gender
female  7.364474    6.25
male    7.177670    6.50

In [ ]:
pd.DataFrame(df.groupby("city"))

           0                                                  1
0  Islamabad      student_id  gender       city program  sem...
1    KARACHI     student_id  gender     city program  semest...
2    Karachi      student_id  gender     city program  semes...
3     Lahore      student_id  gender    city program  semest...
4     Multan      student_id  gender    city program  semest...
5   PESHAWAR      student_id  gender      city program  seme...
6   Peshawar      student_id  gender      city program  seme...
7     Quetta      student_id  gender    city program  semest...

:

In [6]:
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [8]:
df.groupby('city').count()

,student_id,gender,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
city,,,,,,,,,
Islamabad,20,20,20,20,20,18,19,20,20
KARACHI,3,3,3,3,3,3,3,3,3
Karachi,33,33,33,33,31,28,30,33,33
Lahore,29,29,29,29,28,26,27,29,29
Multan,19,19,19,19,18,17,19,19,19
PESHAWAR,3,3,3,3,3,3,3,3,3
Peshawar,55,55,55,55,54,51,53,55,55
Quetta,22,22,22,22,22,22,20,22,22